name: mimu
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  phosphor_flutter: ^2.0.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  provider: ^6.1.1
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  record: ^5.2.1
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  webview_flutter: ^4.4.2
  share_plus: ^7.2.1
  http: ^1.1.0
  web_socket_channel: ^3.0.1
  flutter_webrtc: ^1.3.0
  flutter_callkit_incoming: ^2.0.0
  pointycastle: ^3.9.1
  crypto: ^3.0.5
  flutter_markdown: ^0.6.18
  linkify: ^5.0.0
  package_info_plus: ^8.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.3.0
  sentry_flutter: ^8.14.2
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  cryptography: ^2.7.0
  blurhash_dart: ^1.2.0
  ed25519_edwards: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  record_linux: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/wordlists/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
